spring:
  application:
    name: tichu-sim
  datasource:
    url: jdbc:mysql://localhost:3306/tichu?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 600    # 10 mins
    refreshTokenExpiration: 7200  # 2 hrs
    webSocketTokenExpiration: 60  # 1 min
  cors:
    allowed-origin: http://localhost:5173
  rooms:
    id-length: 5
